### ISSUE TITLE
@es-git/memory-repo is published as @es-git/__template__ instead

### ISSUE THREAD

**Issue by SpiralP** [es-git/es-git#1]
The `package.json` for `memory-repo` has an incorrect name:
https://github.com/es-git/es-git/blob/274e135739a1341696e260037739c7a45b5db493/packages/memory-repo/package.json#L2

So the package was published to [@es-git/\_\_template\_\_](https://www.npmjs.com/package/@es-git/__template__) instead of [@es-git/memory-repo](https://www.npmjs.com/package/@es-git/memory-repo).

**Comment by mariusGundersen** [comment]
Thanks for letting me know, I noticed this as well yesterday 🙈

I will publish a new version sometime in the next few days. I'm not sure what to do with the published template, since npm doesn't allow it to be deleted. Any ideas?

**Comment by SpiralP** [comment]
I think you can do `npm unpublish @es-git/__template__` which will make the page 404, but will keep the package name owned by yourself, and won't let you publish on the same version number.

**Comment by mariusGundersen** [comment]
I tried to unpublish, but after the whole left-pad thing it's not that easy anymore. Maybe I can contact npm, but that seems like a big effort. I think it can be deprecated and point to another package.

**Comment by mariusGundersen** [comment]
Fixed now 😀
