### ISSUE TITLE
repo for demos?

### ISSUE THREAD

**Issue by tomByrer** [es-git/es-git#12]
I"m trying to get a better grasp on ES-git, but Google isn't helping to find examples.  Could you post the repos for your online demos please?  Ekkiog is a bit too big to ramp up on.

BTW, I like the mixins idea.

TIA

**Comment by mariusGundersen** [comment]
The examples are in the [examples](https://github.com/es-git/es-git/tree/master/packages/example) package, in the monorepo. The push example is probably the most complete one.

**Comment by tomByrer** [comment]
Thanks!  I was expecting examples to be in the root folder or in  a [/docs](https://pages.github.com/) folder.
(Seems `/docs` is the new GH recommended standard vs `.github-pages` branch).
