### ISSUE TITLE
Having trouble with the deployment key.

### ISSUE THREAD

**Issue by gijswijs** [es-git/es-git#6]
The example uses environment variable of Node to get the key stored in process.env.KEY
I assumed it's a deploy key of the repository.
And it should be set with the contents of the private key of that key pair, am I correct?

So I cloned the test-push repository, and created a deploy Key, and adjusted server.js and push.ts to point to my own repositories.

If I leave the KEY empty I get a 401 (Authorization Required) which seems expected.

But if I use the private key, I get 500 server error on this resource: http://localhost:8080/proxy/github.com/gijswijs/test-push.git/git-receive-pack

Any help is appreciated.

**Comment by gijswijs** [comment]
I just thought of something... It's basic authentication, so it's just the base64 of the username and password, right? I'll try that tomorrow and report back.

**Comment by mariusGundersen** [comment]
Yes, it's using basic authentication of `username:password` or `username:oaut_token`. You can use [Grant](https://github.com/simov/grant) to connect to a github application and get an `oauth_token`. I don't have an example in es-git, but I have it implemented [here](https://github.com/mariusGundersen/Ekkiog/blob/master/server.js)

**Comment by gijswijs** [comment]
That worked flawlessly. Thanks!
