### ISSUE TITLE
@es-git/fetch-mixin Syntax error

### ISSUE THREAD

**Issue by fuel-wlightning** [es-git/es-git#9]
When trying to load @es-git/fetch-mixin I get errors.

On RunKit site (linked from npm module page)[1] I get the error "SyntaxError: Unexpected token export" on all node versions except 10.

When I try the same locally, I get the following:

> FM-WILLIG2-MAC:testgit williamlightning$ npm install && node index.js
> npm notice created a lockfile as package-lock.json. You should commit this file.
> npm WARN testgit@1.0.0 No description
> npm WARN testgit@1.0.0 No repository field.
> 
> added 10 packages in 48.793s
> /Users/williamlightning/Documents/Projects/working/testgit/node_modules/@es-git/core/es/index.js:1
> (function (exports, require, module, __filename, __dirname) { export { decode, encode, concat, flatten, fromDec, fromHex, fromOct, fromDecChar, fromHexChar, packHash, unpackHash, toHexChar, NEWLINE } from './utils';
>                                                               ^^^^^^
> 
> SyntaxError: Unexpected token export
>     at new Script (vm.js:51:7)
>     at createScript (vm.js:138:10)
>     at Object.runInThisContext (vm.js:199:10)
>     at Module._compile (module.js:626:28)
>     at Object.Module._extensions..js (module.js:673:10)
>     at Module.load (module.js:575:32)
>     at tryModuleLoad (module.js:515:12)
>     at Function.Module._load (module.js:507:3)
>     at Module.require (module.js:606:17)
>     at require (internal/module.js:11:18)
> FM-WILLIG2-MAC:testgit williamlightning$

package.json is:
```
{
  "name": "testgit",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "SEE LICENSE IN NO LICENSE",
  "dependencies": {
    "@es-git/fetch-mixin": "^0.8.3",
    "babel-runtime": "^6.26.0"
  }
}
```

index.js is:
```
var fetchMixin = require("@es-git/fetch-mixin");
```

Local node & npm versions:

> FM-WILLIG2-MAC:~ williamlightning$ npm -v
> 5.6.0
> FM-WILLIG2-MAC:~ williamlightning$ node --version
> v9.6.1
> FM-WILLIG2-MAC:~ williamlightning$

* [1] https://npm.runkit.com/@es-git/fetch-mixin

**Comment by mariusGundersen** [comment]
Hmm, that's strange. I'm currently on holiday, so I can't look into this problem right now, as I don't have access to a machine with node. What I'm thinking is that it's either an issue with node 10 (which I haven't tested it on yet) or it's something wrong with the package.json files. Can you test it on node 8 for me?

**Comment by fuel-wlightning** [comment]
Thank you for taking time during your holiday to respond!

Below are runkit links for each version:

- With Node 9: https://runkit.com/embed/zkkxhrrxznv8
- With Node 8: https://runkit.com/embed/piuum9pi4vvk
- With Node 7: https://runkit.com/embed/vdfq6n3xh936
- With Node 6: https://runkit.com/embed/ltenzvpq1tfc
- With Node 5: https://runkit.com/embed/50t78qy0rhr4
- With Node 4: https://runkit.com/embed/byyxzqiz27br

The above issue **does not** apply to Node 10. That fails with a different error.

**Comment by mariusGundersen** [comment]
In the first error message it says `@es-git/core/es/index.js:1`, which indicates that it loads the intermediate output from the `/es/` folder, the result of compiling the typescript code to ES2017 code. It should load the final output from the `/js/` folder, which is the result of running Babel on the `/es/` folder. I don't know why it's choosing this folder, as the [package json file of the core package](https://github.com/es-git/es-git/blob/master/packages/core/package.json) has a `"main"` field that points to `js/index.js`.

It would be nice to check what the transpiled packages look like, but I'm unable to do that currently, without a computer. I'll take a look next week when I'm back

**Comment by mariusGundersen** [comment]
Ok, looked into it now and found the issue: the fetch-mixin was doing a relative import (probably added by Visual Studio Code refactoring) instead of module import. I'll have a fix out very quickly!

Thanks for finding this for me! :1st_place_medal:

**Comment by fuel-wlightning** [comment]
You rock! Thanks for putting together this awesome project!

**Comment by fuel-wlightning** [comment]
Verified fixed. Thank you!
